const foodItem=[
    //--------------------------------------soup-------------------------------------
    {
        id:1,
        name :'Rice with soup',
        category : 'soup',
        rating: 4.3,
        price: 60,
        img: 'rice,chicken-fried.jpg',
        quantity:1,
    },
    {
        id:2,
        name :'Rice with fishsoup',
        category : 'soup',
        rating: 4.3,
        price:60,
        img: 'fish,soup.jpg',
        quantity:1,
    },
    {
        id:3,
        name :'Chicken Rice',
        category : 'soup',
        rating: 4.3,
        price:70,
        img: 'rice,soup1.jpg',
        quantity:1,
    },
    {
        id:4,
        name :'Rice Soup',
        category : 'soup',
        rating: 4.3,
        price:70,
        img: 'rice,soup2.jpg',
        quantity:1,
    },    
    //--------------------------------------fried-------------------------------------
    {
        id:5,
        name :'Chicken Rice 1',
        category : 'fried',
        rating: 4.3,
        price:80,
        img: 'rice,chicken-fried.jpg',
        quantity:1,
    },    
    {
        id:6,
        name :'Rice Egg',
        category : 'fried',
        rating: 4.3,
        price:50,
        img: 'rice,egg.jpg',
        quantity:1,
    },    
    {
        id:7,
        name :'Rice with Fish',
        category : 'fried',
        rating: 4.3,
        price:60,
        img: 'rice,fish1.jpg',
        quantity:1,
    },    
    {
        id:8,
        name :'Rice with Fish1',
        category : 'fried',
        rating: 4.3,
        price:60,
        img: 'rice,fish2.jpg',
        quantity:1,
    },    
    {
        id:9,
        name :'Rice with Fish2',
        category : 'fried',
        rating: 4.3,
        price:70,
        img: 'rice,fish3.jpg',
        quantity:1,
    },    
    {
        id:10,
        name :'Rice with Fish3',
        category : 'fried',
        rating: 4.3,
        price:60,
        img: 'rice,fish4.jpg',
        quantity:1,
    },
    //--------------------------------------curry and snack-------------------------------------
    {
        id:11,
        name :'Curry',
        category : 'curry',
        rating: 4.3,
        price:70,
        img: 'curry.jpg',
        quantity:1,
    },
    {
        id:12,
        name :'Snack 1',
        category : 'curry',
        rating: 4.3,
        price:50,
        img: 'snack1.png',
        quantity:1,
    },
    {
        id:13,
        name :'Snack 2',
        category : 'curry',
        rating: 4.3,
        price:50,
        img: 'snack2.png',
        quantity:1,
    }
]
export {foodItem};
